# Generated by Django 4.1.5 on 2023-01-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('landing_image', models.ImageField(upload_to='images/')),
                ('landing_title', models.TextField(max_length=250)),
            ],
        ),
    ]
