# Generated by Django 4.1.6 on 2023-02-02 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postl',
        ),
        migrations.CreateModel(
            name='Postr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='posts/')),
                ('post_title', models.CharField(max_length=250)),
                ('post_content', models.TextField()),
                ('post_date', models.DateField()),
                ('post_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
