# Generated by Django 4.1.6 on 2023-02-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_post_postl_postr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postl',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts left'},
        ),
        migrations.AlterModelOptions(
            name='postr',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts right'},
        ),
        migrations.CreateModel(
            name='Postarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_image', models.ImageField(upload_to='posts')),
                ('archive_title', models.CharField(max_length=150)),
                ('archive_content', models.TextField()),
                ('archive_date', models.DateField()),
                ('archive_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archive post yaratish',
            },
        ),
    ]
