# Generated by Django 4.1.6 on 2023-02-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_postl_options_alter_postr_options_postarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarchive',
            name='archive_author',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
