# Generated by Django 4.1.6 on 2023-02-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postarchive_archive_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
