# Generated by Django 4.1.6 on 2023-02-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
