# Generated by Django 4.1.6 on 2023-02-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postarchive',
            old_name='archive_category',
            new_name='category',
        ),
    ]
